services:
  - type: web
    name: api-compras
    env: node
    buildCommand: |
      npm install
      apt-get update && apt-get install -y chromium chromium-browser
    startCommand: npm start
    envVars:
      - key: CHROMIUM_PATH
        value: /usr/bin/chromium-browser
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true" 